#!/usr/bin/env python3
"""
Offline Feature Alignment: distill SAM 3's native text-encoder output into
the V7 Bridge using a purely-text dataset.

Teacher:  SAM 3's language_backbone (VETextEncoder, frozen).
          Consumes the description (with <|seg|> stripped) and emits the
          CLIP-style global summary token — specifically the 256-d vector
          at the EOS (<|endoftext|>) position of `text_memory_resized`.
          SAM 3's text backbone is CLIP-derived and packs the sentence
          representation into that single token; mean-pooling would
          dilute the sharp semantic/geometric focus we want to distill.

Student:  Qwen [SEG] hidden state (4096D, from frozen Qwen3-VL's
          language model) -> trainable V7 Bridge (4096 -> 1024) ->
          SAM 3's frozen resizer (1024 -> 256).

Loss:     1 - cos(student, teacher), averaged across the batch
          (user asked for CosineEmbeddingLoss-style objective).
          MSE also available via --loss mse.

Validation (the real signal):
  Every `--val-every` optimiser steps, we run the RWTD Bridge Oracle
  evaluator on the CURRENT Bridge weights and report true mIoU. The
  best Bridge state (highest Oracle mIoU) is saved to
  `aligned_bridge_best.pt`.

RWTD is used ONLY for validation. It is never in the training stream.
The entire training dataset comes from `offline_alignment_dataset.json`
(generated by scripts/generate_alignment_data.py).

Usage:
    python scripts/offline_text_alignment.py \\
        --dataset offline_alignment_dataset.json \\
        --rwtd-gt RWTD_GT.json \\
        --output-dir checkpoints/offline_align \\
        --batch-size 128 --epochs 3 --lr 1e-4 --val-every 500
"""

import argparse
import json
import logging
import math
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

from models.qwen2sam_detexture import (
    Qwen2SAMDeTexture, SEG_TOKEN, MAX_TEXTURES,
)
from models.bridge import BridgeProjector
from training.utils import load_config, save_checkpoint, load_checkpoint
from scripts.evaluate_bridge_oracle import (
    load_rwtd_sample, hungarian_miou, oracle_forward_one,
)
from data.dataset import DeTextureCollator, build_assistant_text

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("offline_align")


# ===================================================================== #
#  Text dataset                                                           #
# ===================================================================== #

class TextAlignmentDataset(Dataset):
    """Wraps a flat list of description strings."""

    def __init__(self, path: str):
        with open(path) as f:
            self.items = json.load(f)
        assert isinstance(self.items, list) and len(self.items) > 0, \
            "dataset must be a non-empty list of strings"
        log.info(f"Loaded {len(self.items)} alignment descriptions from {path}.")

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        return self.items[idx]


def text_collate(batch: list[str]) -> dict:
    """Pass-through collator: return batch list as-is; tokenisation happens
    on-device to avoid CPU-side fan-out during training."""
    return {"texts": batch}


# ===================================================================== #
#  Target extraction — SAM 3's native 256-d per-text representation       #
# ===================================================================== #

@torch.no_grad()
def sam_text_target(sam3, texts_stripped: list[str], device) -> torch.Tensor:
    """Extract the CLIP-style EOS (<|endoftext|>) token embedding from
    SAM 3's text encoder. Returns shape (batch, 256).

    Why EOS and not mean-pool:
      SAM 3's VETextEncoder is CLIP-derived — it runs a causal text
      transformer with pool_type='none' and preserves the full sequence
      of per-token 256-d vectors. Per CLIP convention, the GLOBAL
      sentence representation is packed into the <|endoftext|> token's
      position, not distributed evenly. Mean-pooling those sequence
      vectors would dilute this focused representation. We therefore
      gather only the EOS row per sample.

    Why argmax works:
      CLIP's BPE tokenizer assigns the highest vocabulary ID
      (typically 49407) to <|endoftext|>, so tokenized.argmax(dim=-1)
      reliably returns the EOS position. SAM 3 inherits this tokenizer
      convention.

    Implementation:
      VETextEncoder.forward() discards the `tokenized` tensor we need
      for the EOS argmax. We therefore replicate its three internal
      steps inline (tokenize -> encoder -> resizer) so we can grab
      both `tokenized` and the resized per-token memory.
    """
    tle = sam3.backbone.language_backbone
    tokenized = tle.tokenizer(
        texts_stripped, context_length=tle.context_length,
    ).to(device)
    # tokenized: (batch, seq_len)
    _, text_memory = tle.encoder(tokenized)
    # text_memory: (batch, seq_len, 1024)  (pool_type='none', output_tokens=True)
    text_memory_resized = tle.resizer(text_memory)
    # text_memory_resized: (batch, seq_len, 256)

    # CLIP convention: EOS position = argmax over token IDs (EOS is the
    # highest-ID special token in the BPE vocab).
    eos_pos = tokenized.argmax(dim=-1)              # (batch,)
    row_idx = torch.arange(tokenized.size(0), device=device)
    target = text_memory_resized[row_idx, eos_pos]  # (batch, 256)
    return target.float()


# ===================================================================== #
#  Student extraction — Qwen [SEG] hidden state                            #
# ===================================================================== #

@torch.no_grad()
def qwen_seg_hidden(qwen, tokenizer, texts: list[str], seg_token_id: int,
                    device, max_length: int = 80) -> torch.Tensor:
    """Text-only forward through Qwen's language-model head. Return the
    hidden state at the <|seg|> position for each sample.

    Note: Qwen3-VL is multimodal but exposes a pure-language path via
    `qwen.model.language_model`. Since we do not have images here, we use
    the language-only path for both speed and GPU-memory economy.

    Expects each text to contain exactly one <|seg|> (our synthesis pipeline
    enforces the TEMPLATE). If more than one is present we take the first.
    If none is present the sample is dropped (by returning NaN rows that
    the caller must filter).
    """
    enc = tokenizer(texts, return_tensors="pt", padding=True, truncation=True,
                    max_length=max_length, add_special_tokens=True).to(device)
    input_ids = enc["input_ids"]           # (B, L)
    attention_mask = enc["attention_mask"]  # (B, L)

    # language_model returns BaseModelOutput with last_hidden_state
    lm = qwen.model.language_model if hasattr(qwen, "model") else qwen
    # PEFT wrapping may expose .base_model.model.model.language_model
    if not hasattr(lm, "forward"):
        lm = qwen.base_model.model.model.language_model
    out = lm(input_ids=input_ids, attention_mask=attention_mask,
             output_hidden_states=False)
    hidden = out.last_hidden_state      # (B, L, 4096)

    # Per sample, find the first SEG position.
    B, L = input_ids.shape
    seg_mask = (input_ids == seg_token_id)  # (B, L)
    any_seg = seg_mask.any(dim=1)
    # argmax on int tensor returns the first True index (argmax of {0,1} on 0s
    # returns 0 too, so we guard with any_seg).
    seg_pos = seg_mask.int().argmax(dim=1)
    # Gather per-sample hidden at seg position.
    idx = seg_pos.view(B, 1, 1).expand(B, 1, hidden.size(-1))
    seg_hidden = hidden.gather(dim=1, index=idx).squeeze(1)  # (B, 4096)
    # Mark missing-seg rows with NaN for later filtering.
    seg_hidden[~any_seg] = float("nan")
    return seg_hidden.float()


# ===================================================================== #
#  Periodic RWTD Oracle validation                                        #
# ===================================================================== #

@torch.no_grad()
def run_rwtd_oracle(model, collator, rwtd_items, device,
                    image_size: int, limit: int = None) -> float:
    """Run the Bridge Oracle on the RWTD sample set using the CURRENT model
    state. Returns the mean mIoU (Hungarian-matched).

    This reuses functions from evaluate_bridge_oracle.py, keeping the
    validation pathway identical to the offline evaluator — no drift.
    """
    model.eval()
    mious = []
    items = rwtd_items[:limit] if limit else rwtd_items
    for it in items:
        crop = it["crop_name"]
        parsed = it.get("parsed", {})
        da, db = parsed.get("desc_a"), parsed.get("desc_b")
        if not (da and db):
            continue
        try:
            image_pil, sam_image, gt_index = load_rwtd_sample(
                crop, image_size=image_size,
            )
        except FileNotFoundError:
            continue
        assistant_text = build_assistant_text([da, db])
        sample = {
            "image": image_pil,
            "assistant_text": assistant_text,
            "sam_image": sam_image,
            "index_mask": torch.from_numpy(gt_index),
            "k_gt": 2,
            "descriptions": [da, db],
            "qwen_gt_embeds": torch.zeros(MAX_TEXTURES, 4096),
        }
        batch = collator([sample])
        try:
            pred, k_pred = oracle_forward_one(model, model.processor, batch, device)
        except torch.cuda.OutOfMemoryError:
            log.warning(f"OOM on RWTD crop {crop}; skipping.")
            torch.cuda.empty_cache()
            continue
        mious.append(hungarian_miou(pred, gt_index, k_pred=k_pred, k_gt=2))
    return float(np.mean(mious)) if mious else 0.0


# ===================================================================== #
#  Main                                                                   #
# ===================================================================== #

def strip_seg_for_sam(texts: list[str]) -> list[str]:
    """SAM uses CLIP's BPE tokeniser — the literal '<|seg|>' would tokenise
    as nonsense for it. Strip it and leading/trailing whitespace."""
    out = []
    for t in texts:
        # remove SEG markers (with optional surrounding whitespace)
        s = t.replace(SEG_TOKEN, "").strip()
        # also drop stray "TEXTURE_N: " prefix if present — SAM doesn't need
        # the indexing, just the semantic body.
        if ":" in s.split(" ", 1)[0]:
            try:
                s = s.split(":", 1)[1].strip()
            except Exception:
                pass
        out.append(s)
    return out


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--config", default="configs/detexture.yaml")
    p.add_argument("--dataset",
                   default=str(_PROJECT_ROOT / "offline_alignment_dataset.json"))
    p.add_argument("--rwtd-gt",
                   default=str(_PROJECT_ROOT / "RWTD_GT.json"))
    p.add_argument("--output-dir",
                   default=str(_PROJECT_ROOT / "checkpoints/offline_align"))
    p.add_argument("--init-from", default=None,
                   help="Optional V7 checkpoint to initialise Bridge weights.")
    p.add_argument("--batch-size", type=int, default=128)
    p.add_argument("--epochs", type=int, default=3)
    p.add_argument("--lr", type=float, default=1e-4)
    p.add_argument("--weight-decay", type=float, default=0.01)
    p.add_argument("--loss", choices=["cosine", "mse"], default="cosine")
    p.add_argument("--val-every", type=int, default=500,
                   help="Run RWTD Oracle every N optimiser steps.")
    p.add_argument("--val-limit", type=int, default=None,
                   help="Optional: evaluate only first N RWTD samples during "
                        "periodic validation (full eval on best).")
    p.add_argument("--num-workers", type=int, default=4)
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    cfg = load_config(args.config)
    device = torch.device("cuda")

    # ------------------------------------------------------------------ #
    # Model
    # ------------------------------------------------------------------ #
    log.info("Building model (Qwen + SAM 3 frozen, Bridge trainable)...")
    model = Qwen2SAMDeTexture(cfg, device=str(device))

    if args.init_from:
        log.info(f"Initialising Bridge from checkpoint {args.init_from}")
        load_checkpoint(model, None, args.init_from, device=str(device))

    # Freeze everything except the Bridge
    for n, p_ in model.named_parameters():
        p_.requires_grad = False
    for p_ in model.bridge.parameters():
        p_.requires_grad = True

    n_bridge = sum(p_.numel() for p_ in model.bridge.parameters())
    log.info(f"Bridge trainable params: {n_bridge:,}")

    # Everything is eval() except the Bridge (for dropout + gradient flow)
    model.eval()
    model.bridge.train()

    tokenizer = model.processor.tokenizer
    seg_token_id = tokenizer.convert_tokens_to_ids(SEG_TOKEN)
    resizer = model._sam_resizer          # frozen Linear(1024, 256)
    sam3 = model.sam3                      # frozen VL backbone
    qwen = model.qwen                      # frozen language model

    # ------------------------------------------------------------------ #
    # Data
    # ------------------------------------------------------------------ #
    train_ds = TextAlignmentDataset(args.dataset)
    train_loader = DataLoader(
        train_ds, batch_size=args.batch_size, shuffle=True,
        num_workers=args.num_workers, collate_fn=text_collate,
        pin_memory=True, drop_last=True,
    )
    log.info(f"Train loader: {len(train_loader)} batches of {args.batch_size}")

    with open(args.rwtd_gt) as f:
        rwtd_items = [it for it in json.load(f) if it.get("parse_ok", False)]
    log.info(f"RWTD validation set: {len(rwtd_items)} samples (parse_ok).")

    image_size = cfg["data"].get("image_size", 1008)
    val_collator = DeTextureCollator(model.processor, inference=False)

    # ------------------------------------------------------------------ #
    # Optimiser + scheduler
    # ------------------------------------------------------------------ #
    optim = torch.optim.AdamW(
        model.bridge.parameters(), lr=args.lr,
        weight_decay=args.weight_decay,
    )
    total_steps = args.epochs * len(train_loader)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optim, T_max=total_steps, eta_min=args.lr * 0.01,
    )
    log.info(f"Total optimiser steps: {total_steps}")

    # ------------------------------------------------------------------ #
    # Training loop
    # ------------------------------------------------------------------ #
    best_miou = -1.0
    best_path = out_dir / "aligned_bridge_best.pt"
    metrics_log = []
    global_step = 0
    t0 = time.time()

    for epoch in range(args.epochs):
        log.info(f"===== Epoch {epoch + 1}/{args.epochs} =====")
        for batch_idx, batch in enumerate(train_loader):
            texts = batch["texts"]

            # Student: Qwen [SEG] hidden state (frozen Qwen)
            try:
                seg_hidden = qwen_seg_hidden(
                    qwen, tokenizer, texts, seg_token_id, device,
                )
            except torch.cuda.OutOfMemoryError:
                log.warning(f"OOM on step {global_step}; dropping batch.")
                torch.cuda.empty_cache()
                continue

            # Drop rows whose SEG position was missing (NaN flagged)
            valid_rows = ~torch.isnan(seg_hidden).any(dim=1)
            if valid_rows.sum().item() == 0:
                continue
            seg_hidden = seg_hidden[valid_rows]
            valid_texts = [t for t, v in zip(texts, valid_rows.tolist()) if v]

            # Teacher: SAM 256-d target (frozen SAM text encoder)
            stripped = strip_seg_for_sam(valid_texts)
            with torch.amp.autocast("cuda", dtype=torch.bfloat16):
                try:
                    target = sam_text_target(sam3, stripped, device)
                except torch.cuda.OutOfMemoryError:
                    log.warning(f"OOM on SAM side at step {global_step}; dropping.")
                    torch.cuda.empty_cache()
                    continue

            # Student forward: Bridge + frozen resizer
            with torch.amp.autocast("cuda", dtype=torch.bfloat16):
                bridge_out = model.bridge(seg_hidden.to(dtype=torch.bfloat16))
                student_256 = resizer(bridge_out).float()

            # Loss
            if args.loss == "cosine":
                loss = 1.0 - F.cosine_similarity(student_256, target, dim=-1).mean()
            else:
                loss = F.mse_loss(student_256, target)

            optim.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.bridge.parameters(), 1.0)
            optim.step()
            scheduler.step()

            global_step += 1

            if global_step % 50 == 0:
                with torch.no_grad():
                    cos_sim = F.cosine_similarity(
                        student_256, target, dim=-1,
                    ).mean().item()
                lr_now = scheduler.get_last_lr()[0]
                log.info(
                    f"  [ep{epoch+1} step {global_step}/{total_steps}] "
                    f"loss={loss.item():.4f}  cos_sim={cos_sim:.4f}  "
                    f"lr={lr_now:.2e}  elapsed={(time.time()-t0)/60:.1f}m"
                )

            # ---- Periodic Oracle validation ------------------------- #
            if global_step % args.val_every == 0:
                log.info(f"  [val] running RWTD Oracle at step {global_step}...")
                t_val = time.time()
                miou = run_rwtd_oracle(
                    model, val_collator, rwtd_items, device,
                    image_size=image_size, limit=args.val_limit,
                )
                val_time = time.time() - t_val
                log.info(f"  [val] step {global_step}: mIoU={miou:.4f} "
                         f"({val_time:.0f}s)")

                metrics_log.append({
                    "step": global_step,
                    "epoch": epoch + 1,
                    "train_loss": float(loss.item()),
                    "val_miou": miou,
                    "val_time_sec": val_time,
                })
                (out_dir / "metrics.json").write_text(
                    json.dumps(metrics_log, indent=2),
                )

                if miou > best_miou:
                    best_miou = miou
                    log.info(f"  [val] new best mIoU={best_miou:.4f} "
                             f"-> {best_path}")
                    save_checkpoint(
                        model, optim, epoch,
                        str(best_path),
                        extra={"val_miou": miou, "step": global_step,
                               "offline_alignment": True},
                    )

                # Back to training mode for Bridge dropout
                model.eval()
                model.bridge.train()

    log.info("\n===== Training complete =====")
    log.info(f"Best RWTD Oracle mIoU: {best_miou:.4f}")
    log.info(f"Best checkpoint: {best_path}")
    log.info(f"Total time: {(time.time() - t0) / 60:.1f} min")


if __name__ == "__main__":
    main()
